# Generated by Django 5.1.4 on 2025-03-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "event_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("event_details", models.TextField()),
                ("event_venue", models.CharField(max_length=255)),
                ("event_date_range", models.CharField(max_length=255)),
                ("event_address", models.TextField()),
                ("event_city", models.CharField(max_length=255)),
                ("event_state", models.CharField(max_length=255)),
                ("event_title_img", models.ImageField(upload_to="event_title_images/")),
                (
                    "event_banner_img",
                    models.ImageField(upload_to="event_banner_images/"),
                ),
                ("digital_pass", models.BooleanField(default=False)),
                ("event_time", models.CharField(max_length=255)),
                ("artist_id", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "artist_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("artist_name", models.CharField(max_length=255)),
                ("artist_image", models.ImageField(upload_to="event_gallery_images/")),
                ("artist_description", models.TextField()),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
