# Generated by Django 5.1.4 on 2025-03-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ticket_price",
            field=models.CharField(default=1999, max_length=255),
            preserve_default=False,
        ),
    ]
