# Generated by Django 5.1.4 on 2025-03-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_ticket_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location_link",
            field=models.CharField(default="", max_length=255),
        ),
    ]
