# Generated by Django 5.1.4 on 2025-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_eventbannerimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="artist_id",
            new_name="artist_description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_banner_img",
        ),
        migrations.RemoveField(
            model_name="eventbannerimage",
            name="event_id",
        ),
        migrations.AddField(
            model_name="event",
            name="artist_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="event_artist_images/"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="artist_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="event_gallery_imgs",
            field=models.ManyToManyField(blank=True, to="events.eventbannerimage"),
        ),
        migrations.AddField(
            model_name="event",
            name="featured_event",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="ticket_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="Artist",
        ),
    ]
