# Generated by Django 5.1.4 on 2025-04-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_contactmessage_homepageimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_id",
            field=models.CharField(
                default="",
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
