# Generated by Django 5.1.4 on 2025-04-04 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_alter_event_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageimages",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_images",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="homepageimages",
            name="image",
            field=models.ImageField(upload_to="homepage_images/"),
        ),
    ]
