# Generated by Django 5.1.4 on 2025-04-04 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_homepageimages_event_alter_homepageimages_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepageimages",
            name="event",
        ),
    ]
