# Generated by Django 5.1.4 on 2025-04-04 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_remove_homepageimages_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepageimages",
            old_name="image",
            new_name="homepage_image",
        ),
    ]
