# Generated by Django 5.1.4 on 2025-04-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_rename_image_homepageimages_homepage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageimages",
            name="image_descruption",
            field=models.CharField(default="", max_length=255),
        ),
    ]
