# Generated by Django 5.1.4 on 2025-04-04 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_homepageimages_image_descruption"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepageimages",
            old_name="image_descruption",
            new_name="image_description",
        ),
    ]
