# Generated by Django 5.1.4 on 2025-04-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_rename_image_descruption_homepageimages_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="whatsapp_message",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="whatsapp_number",
            field=models.CharField(default="", max_length=255),
        ),
    ]
