# Generated by Django 5.1.4 on 2025-04-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_event_whatsapp_message_event_whatsapp_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_size", models.CharField(default="", max_length=255)),
                ("product_description", models.TextField()),
                ("product_price", models.CharField(max_length=255)),
                ("product_image", models.ImageField(upload_to="productsimages/")),
                ("product_link", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="eventbannerimage",
            name="banner_image",
            field=models.FileField(upload_to="event_banner_images/"),
        ),
    ]
