# Generated by Django 5.1.4 on 2025-04-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_products_alter_eventbannerimage_banner_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="id",
        ),
        migrations.AddField(
            model_name="products",
            name="product_id",
            field=models.CharField(
                default="",
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="whatsapp_message",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="products",
            name="whatsapp_number",
            field=models.CharField(default="", max_length=255),
        ),
    ]
