# Generated by Django 5.1.4 on 2025-04-29 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_remove_products_id_products_product_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="product_link",
        ),
    ]
