# Generated by Django 5.1.4 on 2025-04-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0016_remove_products_product_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_image", models.FileField(upload_to="product_images/")),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="product_gallery_imgs",
            field=models.ManyToManyField(blank=True, to="events.productimage"),
        ),
    ]
